"""Mode-independent public and state artifact contracts."""

from ..artifacts import ARTIFACT_COLUMNS


DISCOVERY_PARQUET_ARTIFACTS = (
    "nodes.parquet",
    "market_groups.parquet",
    "propositions.parquet",
    "relation_candidates.parquet",
    "logic_edges.parquet",
    "conditional_edges.parquet",
    "parse_assessments.parquet",
    "model_assessments.parquet",
    "quarantined_pairs.parquet",
    "qualification_cases.parquet",
    "rejected_edges.parquet",
    "parse_errors.parquet",
    "event_summary.parquet",
    "event_relation_summary.parquet",
    "component_summary.parquet",
    "node_metrics.parquet",
    "visualization_layout.parquet",
)
DISCOVERY_JSON_ARTIFACTS = ("coverage_summary.json", "viewer_manifest.json")
GRAPH_DATABASE_ARTIFACT = "oddsfox_graph.duckdb"
STATE_ARTIFACTS = (
    "state/market_state.parquet",
    "state/proposition_fingerprints.parquet",
    "state/proposition_embeddings.parquet",
    "state/semantic_neighbors.parquet",
    "state/candidate_components.parquet",
    "state/candidate_blocks.parquet",
    "state/candidate_reason_rows.parquet",
    "state/solver_components.parquet",
    "state/execution_plan.parquet",
)

PROPOSITION_COLUMNS = {
    "proposition_id": "VARCHAR",
    "market_id": "VARCHAR",
    "event_id": "VARCHAR",
    "event_slug": "VARCHAR",
    "clob_token_id": "VARCHAR",
    "outcome_index": "INTEGER",
    "outcome": "VARCHAR",
    "question": "VARCHAR",
    "description": "VARCHAR",
    "market_source_hash": "VARCHAR",
    "normalization_version": "VARCHAR",
    "category": "VARCHAR",
    "tags": "VARCHAR[]",
    "subject_original": "VARCHAR[]",
    "subject": "VARCHAR[]",
    "predicate": "VARCHAR",
    "object_original": "VARCHAR",
    "object": "VARCHAR",
    "operator": "VARCHAR",
    "threshold": "DOUBLE",
    "unit_original": "VARCHAR",
    "unit": "VARCHAR",
    "time_start": "TIMESTAMPTZ",
    "time_end": "TIMESTAMPTZ",
    "competition_original": "VARCHAR",
    "competition": "VARCHAR",
    "event_scope_original": "VARCHAR",
    "event_scope": "VARCHAR",
    "jurisdiction_original": "VARCHAR",
    "jurisdiction": "VARCHAR",
    "polarity": "VARCHAR",
    "parse_confidence": "DOUBLE",
    "parse_status": "VARCHAR",
    "primary_parser_model": "VARCHAR",
    "verifier_parser_model": "VARCHAR",
    "prompt_version": "VARCHAR",
    "primary_parse_fingerprint": "VARCHAR",
    "verifier_parse_fingerprint": "VARCHAR",
    "consensus_fingerprint": "VARCHAR",
    "automation_profile_id": "VARCHAR",
    "source_schema": "VARCHAR",
    "extractor_id": "VARCHAR",
    "extractor_version": "VARCHAR",
    "extraction_status": "VARCHAR",
    "source_spans_json": "VARCHAR",
    "proof_scope_key": "VARCHAR",
    "team_name": "VARCHAR",
    "stage_key": "VARCHAR",
    "stage_rank": "INTEGER",
    "progression_level": "INTEGER",
    "market_direction": "VARCHAR",
    "progression_outcome": "VARCHAR",
    "is_progression": "BOOLEAN",
    "market_status": "VARCHAR",
    "is_still_alive": "BOOLEAN",
    "opposite_clob_token_id": "VARCHAR",
    "market_volume_usd": "DOUBLE",
}

REJECTED_EDGE_COLUMNS = {
    "proposal_id": "VARCHAR",
    "src_node_id": "VARCHAR",
    "dst_node_id": "VARCHAR",
    "edge_type": "VARCHAR",
    "edge_basis": "VARCHAR",
    "confidence": "DOUBLE",
    "discovery_method": "VARCHAR",
    "rule_id": "VARCHAR",
    "rule_version": "VARCHAR",
    "prompt_version": "VARCHAR",
    "rejection_reason": "VARCHAR",
    "conflicting_proposal_ids": "VARCHAR[]",
    "conflicting_constraint_ids": "VARCHAR[]",
    "solver_component_id": "VARCHAR",
    "primary_model_version": "VARCHAR",
    "verifier_model_version": "VARCHAR",
    "primary_assessment_id": "VARCHAR",
    "verifier_assessment_id": "VARCHAR",
    "primary_inference_fingerprint": "VARCHAR",
    "verifier_inference_fingerprint": "VARCHAR",
    "consensus_fingerprint": "VARCHAR",
    "automation_profile_id": "VARCHAR",
}

PARSE_ERROR_COLUMNS = {
    "error_id": "VARCHAR",
    "proposition_id": "VARCHAR",
    "market_id": "VARCHAR",
    "error_kind": "VARCHAR",
    "error_message": "VARCHAR",
    "cache_state": "VARCHAR",
    "error_type": "VARCHAR",
    "status_code": "INTEGER",
    "response_json": "VARCHAR",
    "question": "VARCHAR",
    "description": "VARCHAR",
    "parse_confidence": "DOUBLE",
    "market_source_hash": "VARCHAR",
    "model_role": "VARCHAR",
    "parser_model": "VARCHAR",
    "prompt_version": "VARCHAR",
    "schema_version": "VARCHAR",
    "normalization_version": "VARCHAR",
}

MARKET_STATE_COLUMNS = {
    "market_id": "VARCHAR",
    "source_hash": "VARCHAR",
    "parse_model": "VARCHAR",
    "parse_prompt_version": "VARCHAR",
    "normalization_version": "VARCHAR",
    "rule_version": "VARCHAR",
}
PROPOSITION_FINGERPRINT_COLUMNS = {
    "proposition_id": "VARCHAR",
    "market_id": "VARCHAR",
    "market_source_hash": "VARCHAR",
    "parse_fingerprint": "VARCHAR",
    "normalization_version": "VARCHAR",
}
CANDIDATE_COMPONENT_STATE_COLUMNS = {
    "component_id": "VARCHAR",
    "component_fingerprint": "VARCHAR",
    "pair_count": "INTEGER",
    "candidate_version": "VARCHAR",
}
SOLVER_COMPONENT_STATE_COLUMNS = {
    "solver_component_id": "VARCHAR",
    "proposal_hash": "VARCHAR",
    "accepted_proposal_ids": "VARCHAR[]",
    "rejected_proposal_ids": "VARCHAR[]",
    "proposal_count": "INTEGER",
    "hard_clause_count": "INTEGER",
    "soft_clause_count": "INTEGER",
    "objective_cost": "BIGINT",
    "solver_version": "VARCHAR",
    "constraint_version": "VARCHAR",
}
NODE_COLUMNS = {
    "node_id": "VARCHAR",
    "market_id": "VARCHAR",
    "outcome_index": "INTEGER",
    "clob_token_id": "VARCHAR",
    "question": "VARCHAR",
    "outcome_label": "VARCHAR",
    "event_slug": "VARCHAR",
    "is_active": "BOOLEAN",
    "is_closed": "BOOLEAN",
    "market_family": "VARCHAR",
    "canonical_proposition": "VARCHAR",
    "proposition_type": "VARCHAR",
    "expected_tokens": "INTEGER",
    "first_seen_ts": "TIMESTAMPTZ",
    "last_seen_ts": "TIMESTAMPTZ",
}
MARKET_GROUP_COLUMNS = {
    "market_id": "VARCHAR",
    "event_slug": "VARCHAR",
    "question": "VARCHAR",
    "market_family": "VARCHAR",
    "num_tokens": "INTEGER",
    "token_ids": "VARCHAR[]",
    "outcome_labels": "VARCHAR[]",
    "is_active": "BOOLEAN",
    "is_closed": "BOOLEAN",
    "first_seen_ts": "TIMESTAMPTZ",
    "last_seen_ts": "TIMESTAMPTZ",
}
LOGIC_EDGE_COLUMNS = {
    name: (
        "DOUBLE"
        if name == "confidence"
        else "VARCHAR[]" if name == "assumptions" else "VARCHAR"
    )
    for name in ARTIFACT_COLUMNS["logic_edges.parquet"]
}

QUALIFICATION_CASE_COLUMNS = {
    "schema_version": "VARCHAR",
    "generator_version": "VARCHAR",
    "case_id": "VARCHAR",
    "record_type": "VARCHAR",
    "partition": "VARCHAR",
    "domain": "VARCHAR",
    "expected_relation": "VARCHAR",
    "source_market_ids": "VARCHAR[]",
    "source_proposition_ids": "VARCHAR[]",
    "generator_id": "VARCHAR",
    "payload_json": "VARCHAR",
    "case_hash": "VARCHAR",
}
