"""Independent version identifiers for discovery pipeline compatibility."""

PARSE_PROMPT_VERSION = "proposition-parse-v3"
CLASSIFY_PROMPT_VERSION = "atomic-relation-v1"
RULE_VERSION = "discovery-rules-v4"
NORMALIZATION_VERSION = "normalization-v3"
DOMAIN_TAXONOMY_VERSION = "domains-v2"
RETRIEVAL_VERSION = "blockwise-cosine-v4"
CANDIDATE_STATE_VERSION = "candidate-components-v4"
EXECUTION_PLAN_VERSION = "execution-plan-v3"
PUBLICATION_VERSION = "discovery-publication-v4"
BENCHMARK_VERSION = "v0.7.0"
BENCHMARK_SCHEMA_VERSION = "benchmark-v2"
SOURCE_SCHEMA = "polymarket-market-snapshot-v1"
