import type { components } from "./generated/api-schema";

export const emptyCoverage: components["schemas"]["CoverageSummary"] = {
  schema_version: "coverage-summary-v2",
  all_market_selection: true,
  input_selection: {
    strategy: "all_eligible_markets",
    input_market_rows: 0,
    input_rows: 0,
    input_propositions: 0,
    invalid_market_rows: 0,
    eligible_markets: 0,
    eligible_propositions: 0,
    selected_markets: 0,
    selected_propositions: 0,
    truncated: false,
  },
  markets: 0,
  propositions: 0,
  events: 0,
  components: 0,
  parsed: 0,
  parse_quarantined: 0,
  candidates: 0,
  classification_eligible: 0,
  classification_assessed: 0,
  classification_unclassified: 0,
  classification_status: "not_applicable",
  classification_coverage: null,
  classification_gap: null,
  accepted_edges: 0,
  rejected_edges: 0,
  quarantined_pairs: 0,
};
